module.exports = {
    "id": "tcdb",
    "name": "同城夺宝",
    "keys": ["tcdbheader", "tcdbheader2", "tcdbheader3", "tcdbheader4", "tcdbheader5", "tcdbheader6", "tcdbheader7", "tcdbheader8", "tcdbheader9", "tcdbheader10", "tcdbheader11", "tcdbheader12", "tcdbheader13", "tcdbheader14", "tcdbheader15", "tcdbheader16", "tcdbheader17", "tcdbheader18", "tcdbheader19", "tcdbheader20"],
    "author": "@ziye",
    "settings": [{
        "id": "tcdbSuffix",
        "name": "当前账号",
        "val": "1",
        "type": "number",
        "desc": "当前抓取ck记录的账号序号，如：1、2、3、4"
    }, {
        "id": "tcdbCount",
        "name": "账号个数",
        "val": "1",
        "type": "number",
        "desc": "指定任务最多跑几个账号，根据抓取的账号数据个数来设值"
    }, {
        "id": "tcdbXYZ",
        "name": "运行概率",
        "val": "100",
        "type": "number",
        "desc": "0关闭，1打开，默认关闭"
    }, {
        "id": "tcdbXH",
        "name": "循环获取ck",
        "val": "1",
        "type": "number",
        "desc": "0关闭，1打开，默认关闭"
    }, {
        "id": "tcdbTX",
        "name": "自动提现",
        "val": "100",
        "type": "number",
        "desc": "0关闭，1打开，默认关闭"
    }, {
        "id": "tcdbnotifyttt",
        "name": "推送控制",
        "val": "1",
        "type": "number",
        "desc": "0关闭，1推送,默认12点以及23点推送"
    }, {
        "id": "tcdbnotifyInterval",
        "name": "通知控制",
        "val": "2",
        "type": "number",
        "desc": "0关闭，1为 所有通知，2为 12，23 点通知，3为 6，12，18，23 点通知"
    }, {
        "id": "tcdbMinutes",
        "name": "推送-通知 分钟控制",
        "val": "10",
        "type": "number",
        "desc": "推送以及通知控制在什么分钟段，可设置0-59,默认0到10"
    }],
    "repo": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/tcdb.js",
    "icons": ["https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/tcdb.png", "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/tcdb.png"],
    "script": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/tcdb.js",
    "icon": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/tcdb.png",
    "favIcon": "mdi-star-outline",
    "favIconColor": "grey",
    "datas": [{
        "key": "tcdbheader",
        "val": ""
    }, {
        "key": "tcdbheader2",
        "val": ""
    }, {
        "key": "tcdbheader3",
        "val": ""
    }, {
        "key": "tcdbheader4",
        "val": ""
    }, {
        "key": "tcdbheader5",
        "val": ""
    }, {
        "key": "tcdbheader6",
        "val": ""
    }, {
        "key": "tcdbheader7",
        "val": ""
    }, {
        "key": "tcdbheader8",
        "val": ""
    }, {
        "key": "tcdbheader9",
        "val": ""
    }, {
        "key": "tcdbheader10",
        "val": ""
    }, {
        "key": "tcdbheader11",
        "val": ""
    }, {
        "key": "tcdbheader12",
        "val": ""
    }, {
        "key": "tcdbheader13",
        "val": ""
    }, {
        "key": "tcdbheader14",
        "val": ""
    }, {
        "key": "tcdbheader15",
        "val": ""
    }, {
        "key": "tcdbheader16",
        "val": ""
    }, {
        "key": "tcdbheader17",
        "val": ""
    }, {
        "key": "tcdbheader18",
        "val": ""
    }, {
        "key": "tcdbheader19",
        "val": ""
    }, {
        "key": "tcdbheader20",
        "val": ""
    }],
    "sessions": [],
    "isLoaded": true
}
